# Generated by Django 4.0.3 on 2022-07-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10000, null=True)),
                ('price', models.FloatField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='Images/')),
            ],
        ),
    ]
